export default [
  {
    id: "1",
    categoryId: "2",
    name: "Samsung Galaxy S20",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 1200,
    image: "/uploads/samsungS20.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "2",
    categoryId: "1",
    name: "Apple iPhone 11",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 953,
    image: "/uploads/iphone11.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "3",
    categoryId: "3",
    name: "Lenovo Z6",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 764,
    image: "/uploads/lenovoZ6.JPG",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "4",
    categoryId: "5",
    name: "Huawei P30 Lite",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 684,
    image: "/uploads/HuaweiP30.jpg",
    cpu: "2.0GHz Kirin 960",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "5",
    categoryId: "4",
    name: "Xiaomi Mi 9T",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 674,
    image: "/uploads/xiaomiMi9.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "6",
    categoryId: "1",
    name: "Apple iphone 7",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 397,
    image: "/uploads/iphone7.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "7",
    categoryId: "1",
    name: "Apple iPhone 11 Pro",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 1150,
    image: "/uploads/iphone11pro.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "8",
    categoryId: "1",
    name: "Apple iPhone 11 Max",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 1299,
    image: "/uploads/iphone11promax.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "9",
    categoryId: "1",
    name: "Apple iPhone XS",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 699,
    image: "/uploads/iphonexs.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "10",
    categoryId: "2",
    name: "Samsung S10 Lite",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 598,
    image: "/uploads/samsungs10l.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "11",
    categoryId: "2",
    name: "Samsung Note 10",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 1132,
    image: "/uploads/samsungn10.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "12",
    categoryId: "2",
    name: "Samsung Galaxy A71",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 486,
    image: "/uploads/samsunga71.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "13",
    categoryId: "3",
    name: "Lenovo K10",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 235,
    image: "/uploads/lenovok10.JPG",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "14",
    categoryId: "3",
    name: "Lenovo Z5s",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 186,
    image: "/uploads/lenovoz5.JPG",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "15",
    categoryId: "3",
    name: "Lenovo S5 Pro",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 169,
    image: "/uploads/lenovos5.JPG",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "16",
    categoryId: "4",
    name: "Xiaomi Black Shark 2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 574,
    image: "/uploads/xiaomishark.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "17",
    categoryId: "4",
    name: "Xiaomi Mi 10 Pro ",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 523,
    image: "/uploads/xiaomiMi10.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "18",
    categoryId: "4",
    name: "Xiaomi Note 8 Pro",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 456,
    image: "/uploads/xiaomiMi8.jpg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "19",
    categoryId: "5",
    name: "Huawei Nova 5T",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 411,
    image: "/uploads/Huawei5t.jpg",
    cpu: "2.0GHz Kirin 960",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "20",
    categoryId: "5",
    name: "Huawei P Smart 2019",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 249,
    image: "/uploads/HuaweiP30.jpg",
    cpu: "2.0GHz Kirin 960",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  },
  {
    id: "21",
    categoryId: "5",
    name: "Huawei P30 Pro",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta",
    price: 954,
    image: "/uploads/HuaweiP30+.jpg",
    cpu: "2.0GHz Kirin 960",
    camera: "8mp (3264x2448)",
    size: "124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)",
    weight: "132 grams (4.7 ounces) with battery",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB, 32GB and RAM 1 GB"
  }
];
